{{- if .Values.configMap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.nameOverride | default (printf "%s-config" (include "deploy-chart.fullname" .)) }}
  labels:
    {{- include "deploy-chart.labels" . | nindent 4 }}
    {{- with .Values.configMap.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.configMap.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- if .Values.configMap.immutable }}
immutable: true
{{- end }}
{{- if .Values.configMap.data }}
data:
  {{- range $key, $value := .Values.configMap.data }}
  {{- if kindIs "string" $value }}
  {{ $key }}: {{ $value | quote }}
  {{- else }}
  {{ $key }}: |
    {{- $value | toYaml | nindent 4 }}
  {{- end }}
  {{- end }}
{{- end }}
{{- if .Values.configMap.binaryData }}
binaryData:
  {{- range $key, $value := .Values.configMap.binaryData }}
  {{ $key }}: {{ $value }}
  {{- end }}
{{- end }}
{{- end }}
